services:
  app:
    image: anant2002/docker_level_three:fastapi_prod
    env_file:
      - .env 
    depends_on:
      redis-cache:
        condition: service_healthy
    
    restart: on-failure

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 3s
      timeout: 10s
      retries: 3

    volumes:
      - ./logs:/app/logs
  redis-cache:
    image: redis:7-alpine
    restart: on-failure

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 3

    volumes:
      - redis-data:/data
volumes:
  redis-data: 
